CODE	FITANDREMANA SY FIHAHIANA NY EKIPA 		SANCTION	UNITE DE MESURE en MGA	
C-ABS-01-TER	ABSENCE DU COACH AVEC LE GROUPE SUR LE TERRAIN	ABSENCE - PISE A PIEDS	2500	APP/HR	
V-ABS-02-TER	ABSENCE DE L'ANIMATEUR AVEC LE GROUPE SUR TERRAIN		2000	APP/HR	
C-ABS-03-ACC	ABSENCE DU COACH LORS D'UN ACCOMPAGNEMENT		5000	ACC	
V-ABS-04-ACC	ABSENCE DE L'ANIMATEUR LORS D'UN ACCOMPAGNEMENT		5000	ACC	
C-NBT-05-ACC	ACCOMPAGNEMENT NON-ABOUTI JUSQU’À LA FIN - COACH		2000	ACC	
V-NBT-06-ACC	ACCOMPAGNEMENT NON-ABOUTI JUSQU’À LA FIN - ANIMATEUR		2000	ACC	
C-ABS-07-MIS	ABSENCE DURANT LA MISSION - COACH		12000	JOUR	
C-ABS-08-MIS	ABSENCE DURANT LA MISSION - ANIMATEUR		10000	JOUR	
C-MAP-09-MIS	MISE A PIED DURANT LA MISSION - COACH		12000	JOUR	
C-MAP-10-MIS	MISE A PIED DURANT LA MISSION - ANIMATEUR		10000	JOUR	
C-APM-11-MIS	ABSENCE APRES-MISSION - COACH		10000	JOUR	
V-APM-12-MIS	ABSENCE APRES-MISSION - ANIMATEUR		5000	JOUR	
M-APM-83-MIS	ABSENCE APRES-MISSION - MAGASINIER		3000	JOUR	
C-ABS-14-NJT	ABSENCE NON JUSTIFIE SUR TANA - COACH		5000	JOUR	
V-ABS-15-NJT	ABSENCE NON JUSTIFIE SUR TANA - ANIMATEUR		10000	JOUR	
M-ABS-16-NJT	ABSENCE NON JUSTIFIE SUR TANA - MAGASINIER		5000	JOUR	
X-ABS-00-SEP	SEPARATION SANS AUTORISATION  AVEC L'EQUIPE SUR MISSION		30000	ACTE	
C-TEL-01-ACC	COACH INJOIGNABLE LORS D'UN ACCOMPAGNEMENT	TELEPHONE	1000	ACC	
V-TEL-02-ACC	ANIMATEUR INJOIGNABLE LORS D'UN ACCOMPAGNEMENT		500	ACC	
C-TEL-03-ACC	APPEL DEBUT ET FIN DES ACCOMPAGNEMENTS		5000	ACC	
M-TEL-84-ACC	MAGASINIER INJOIGNABLE DURANT LE VERSEMENT A LA  BANQUE 		2000	JOUR	
C-PNG-01-TER	NON RESPECT DU PLANNING SUR TERRAIN - COACH	NON RESPECT DES PLANNIFICATIONS	20000	INFRACTION	
V-PNG-02-TER	NON RESPECT DU PLANNING SUR TERRAIN - ANIMATEUR		10000	INFRACTION	
C-PNG-03-PRD	NON RESPECT DU PLANNING PRODUITS - COACH		20000	INFRACTION	
V-PNG-04-PRD	NON RESPECT DU PLANNING PRODUITS - ANIMATEUR		10000	INFRACTION	
C-PNG-05-MIS	DESISTEMENT 5 J AVANT LE DEBUT D'UNE MISSION - COACH		40000	MISSION	
V-PNG-06-MIS	DESISTEMENT 5 J AVANT LE DEBUT D'UNE MISSION - ANIMATEUR		30000	MISSION	
M-PNG-87-MIS	DESISTEMENT 5 J AVANT LE DEBUT D'UNE MISSION - MAGASINIER		20000	MISSION	
C-VTE-08-PRD	VENTE D'AUTRES PRODUITS - COACH		SPS		
V-VTE-09-PRD	VENTE D'AUTRES PRODUITS - ANIMATEUR		SPS		
M-VTE-10-PRD	VENTE D'AUTRES PRODUITS - MAGASINIER		SPS		
C-ABD-01-MIS	ABANDON SUR MISSION - COACH	ABANDON DE POSTE	SPS	ACTE	SANS PAIEMENT DE SOLDE
V-ABD-02-MIS	ABANDON SUR MISSION - ANIMATEUR		SPS	ACTE	SANS PAIEMENT DE SOLDE
C-ABD-03-3JR	ABANDON DE POSTE - 3J - COACH		30000	ACTE	
V-ABD-04-3JR	ABANDON DE POSTE - 3J - ANIMATEUR		25000	ACTE	
C-DEM-05-SPV	DEMISSION SANS PREAVIS - COACH		30000	ACTE	
V-DEM-06-SPV	DEMISSION SANS PREAVIS - ANIMATEUR		25000	ACTE	
M-DEM-87-SPV	DEMISSION SANS PREAVIS - MAGASINIER		22500	ACTE	
C-COM-01-COM	COMPLICITE - COACH	COMPLICITE - FIRAISANA MITSIKOMBAKOMBA 	70000	ACTE	
V-COM-02-COM	COMPLICITE - ANIMATEUR		70000	ACTE	
M-COM-83-COM	COMPLICITE - MAGASINIER		70000	ACTE	
C-VOL-01-PRX	CHANGEMENT DE PRIX - COACH	VERSEMENT et PRIX	5000	ACTE	
A-VOL-02-PRX	CHANGEMENT DE PRIX - ANIMATEUR		20000	ACTE	
C-VRS-01-RTD	RETARD SUR VERSEMENT - CHEF DE MISSION		0,4	FRAIS M'VOLA	
V-VRS-02-RTD	RETARD SUR VERSEMENT - COACH		0,2	FRAIS M'VOLA	
M-VRS-83-RTD	RETARD SUR VERSEMENT - MAGASINIER		0,4	FRAIS M'VOLA	
C-VRS-01-NFT	VERSEMENT NON FAIT - CHEF DE MISSION		0,05	VERSEMENT	
V-VRS-02-NFT	VERSEMENT NON FAIT - COACH		0,05	VERSEMENT	
M-VRS-83-NFT	VERSEMENT NON FAIT - MAGASINIER		0,05	VERSEMENT	
C-VRS-01-M10	MANQUES SUR VERSEMENT MOINS DE 10.000 MGA VALIDES PAR LE COACH		1000	MQ/ANIM	
C-VRS-03-P10	MANQUES SUR VERSEMENT PLUS DE 10.000 MGAVALIDES PAR LE COACH		15000	MQ/ANIM	
C-VRS-05-M3J	MANQUES SUR VERSEMENT  VALIDES PAR LE COACH -3J AVANT FIN		30000	MQ/ANIM	
C-VRS-07-MNQ	MANQUES SUR VERSEMENT DU COACH		1	MANQUES	
V-VRS-06-MNQ	MANQUES SUR VERSEMENT - ANIMATEUR		0,2	MANQUES	
V-VRS-06-M05	MANQUES SUR VERSEMENT - ANIMATEUR - 5 JOUR AVANT FIN		1	MANQUES	
M-VRS-88-AMQ	MANQUES SUR VERSEMENT  ACCEPTE PAR LE MAGASINIER		1000	MQ/ANIM	
M-VRS-89-M05	MANQUES SUR VERSEMENT  ACCEPTE PAR LE MAGASINIER - 5J AVANT FIN		0,5	MANQUES	
M-VRS-83-MNQ	MANQUES SUR VERSEMENT  DU MAGASINIER		0,3	MANQUES	
C-VRS-01-DCL	FAUSSE DECLARATION SUR VERSEMENT - COACH		70000	ACTE	
V-VRS-02-DCL	FAUSSE DECLARATION SUR VERSEMENT -ANIMATEUR		70000	ACTE	
M-VRS-84-DCL	FAUSSE DECLARATION SUR VERSEMENT - MAGASINIER		70000	ACTE	
C-VRS-03-APC	ECART SUR APERCU DE VENTE - COACH		1000	JOUR	
V-VRS-06-APC	ECART SUR APERCU DE VENTE - ANIMATEUR		250	JOUR	
RAS	RIEN A SIGNALER		0		
X-BON-00-INF	BONUS SUR INFRACTIONS		5000	INFRACTION	